store-app/Components/CartSummaryViewComponent.cs
using Entities.Models;
using Microsoft.AspNetCore.Mvc;

namespace store_app.Components
{
    public class CartSummaryViewComponent: ViewComponent
    {
        public readonly Cart _cart;

        public CartSummaryViewComponent(Cart cartService)
        {
            _cart = cartService;
        }
        public string Invoke()
        {
            return _cart.Lines.Count().ToString();
        }
    }
}

store-app/Components/ProductSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;

namespace store_app.Components
{
    public class ProductSummaryViewComponent: ViewComponent
    {
        public readonly IServiceManager _manager;

        public ProductSummaryViewComponent(IServiceManager manager)
        {
            _manager = manager;
        }

        public string Invoke()
        {
            return _manager.ProductService.GetAllProducts(false).Count().ToString();
        }
    }
}

store-app/Controllers/CategoryController.cs
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Repositories.Contracts;

namespace store_app.Controllers
{
    public class CategoryController: Controller
    {
        private readonly IRepositoryManager _manager;

        public CategoryController(IRepositoryManager manager)
        {
            _manager = manager;
        }

        public IActionResult Index()
        {
            var model = _manager.Category.FindAll(false);
            return View(model);
        }
    }
}

store-app/Controllers/ProductController.cs
using Entities.Models;
using Entities.RequestParameters;
using Microsoft.AspNetCore.Mvc;
using Repositories.Contracts;
using Services.Contracts;
using store_app.Models;


namespace store_app.Controllers
{
    public class ProductController: Controller
    {
        private readonly IServiceManager _manager;

        public ProductController(IServiceManager manager)
        {
            _manager = manager;
        }

        public ActionResult Index(ProductRequestParameters p)
        {
            var products = _manager.ProductService.GetAllProductsWithDetails(p);
            var pagination = new Pagination()
            {
                CurrentPage = p.PageNumber,
                ItemsPerPage = p.PageSize,
                TotalItems = _manager.ProductService.GetAllProducts(false).Count()
            };

            return View(new ProductListViewModel()
            {
                Products = products,
                Pagination = pagination
            });
        }

        public ActionResult Get([FromRoute(Name="id")] int id)
        {
            var model = _manager.ProductService.GetOneProduct(id, false);
            return View(model);
        }
    }
}

store-app/Views/Shared/_Footer.cshtml
<div class="bg-light border-top p-3">
    <div class="container">
        <div class="row">
            <div class="col-md-2">
                <div class="lead text-center ">
                    <i class="fa-solid fa-store text-secondary display-6"></i>
                </div>
                <div class="text-muted text-center">
                    Store App
                </div>
            </div>
            <div class="col-md-8">
                <div class="text-center text-muted my-3">
                    &copy; 2025
                </div>
                <div class="text-center">
                    <div class="btn-group">
                        <a class="btn btn-secondary">
                            <i class="fa-brands fa-facebook"></i>
                        </a>
                        <a class="btn btn-secondary">
                            <i class="fa-brands fa-twitter"></i>
                        </a>
                        <a class="btn btn-secondary">
                            <i class="fa-brands fa-linkedin"></i>
                        </a>
                        <a class="btn btn-secondary">
                            <i class="fa-brands fa-youtube"></i>
                        </a>
                        <a class="btn btn-secondary">
                            <i class="fa-brands fa-instagram"></i>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-md-2">
                <div products="" number="6"></div>
            </div>
        </div>
    </div>
</div>

store-app/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - store_app</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/store_app.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">store_app</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - store_app - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

store-app/Views/Shared/_LoginMenu.cshtml
@if(User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
    <li class="nav-item">
        <a class="nav-link" asp-area="Admin" asp-controller="Dashboard" asp-action="Index">Admin</a>
    </li>
}

@if(User.Identity.IsAuthenticated)
{
    <li class="nav-item">
        <a class="nav-link" asp-area="" asp-controller="Account" asp-route-returnUrl="@Context.Request.PathAndQuery()" asp-action="Logout">Logout</a>
    </li>
}
else
{
    <li class="nav-item">
        <a class="nav-link" asp-area="" asp-controller="Account" asp-route-returnUrl="@Context.Request.PathAndQuery()" asp-action="Login">Login</a>
    </li>
}

store-app/Views/Shared/_Navbar.cshtml
<nav class="navbar bg-light border-bottom navbar-expand-lg bg-body-tertiary">
  <div class="container">
    <a class="navbar-brand" href="/"><i class="fa-solid fa-store fa-2x text-secondary"></i></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
      aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between" id="navbarNavAltMarkup">
      <ul class="navbar-nav flex-grow-1">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" asp-controller="Home" asp-action="Index">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" asp-controller="Product" asp-action="Index">Products (@await Component.InvokeAsync("ProductSummary"))</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" asp-controller="Category" asp-action="Index">Categories</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" asp-page="/Contact">Contact</a>
        </li>
      </ul>
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" asp-page="/cart">
            <i class="fa-solid fa-shopping-cart"></i>
            Cart (@await Component.InvokeAsync("CartSummary"))
          </a>
        </li>
        <partial name="_LoginMenu"></partial>
      </ul>
    </div>
  </div>
</nav>

store-app/Views/Shared/_ProductCard.cshtml
@model Product


<div class="col-md-4 my-3">
    <div class="card" style="width: 18rem;">
        <div class="card-header text-center">@Model.ProductName</div>
        <img src="@Model?.ImageUrl" class="card-img-top" alt="...">
        <div class="card-body">
            <div class="card-text">
                <div class="text-danger text-center lead p-2 rounded-2">
                    @Model?.Price.ToString("c2")
                </div>
            </div>
            <p class="card-text">@Model?.Summary</p>
            <div class="d-flex justify-content-center">
                <div class="btn btn-group">
                    <a asp-controller="Product" asp-action="Get" asp-route-id="@Model?.ProductId" class="btn btn-outline-secondary rounded-2">
                        <i class="fa-solid fa-arrow-right"></i>
                    </a>

                    <form id="@Model?.ProductId" asp-page="/cart" method="post">
                        <input type="hidden" asp-for="ProductId" />
                        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
                        <button type="submit" class="btn btn-outline-secondary mx-1">
                            <i class="fa fa-cart-plus"></i>
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>