store-app/Areas/Admin/Controllers/ProductController.cs
using Entities.Dtos;
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Services.Contracts;

namespace store_app.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductController : Controller
    {
        public readonly IServiceManager _manager;

        public ProductController(IServiceManager manager)
        {
            _manager = manager;
        }

        public IActionResult Index()
        {
            var model = _manager.ProductService.GetAllProducts(false);
            return View(model);
        }

        public IActionResult Create()
        {
            ViewBag.Categories = GetCategoriesSelectList();
            return View();
        }

        private SelectList GetCategoriesSelectList()
        {
            return new SelectList(_manager.CategoryService.GetAllCategories(false), "CategoryId", "CategoryName", "1");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([FromForm] ProductDtoForInsertion productDto, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                string path = Path.Combine(Directory.GetCurrentDirectory(), 
                "wwwroot", "images", file.FileName);

                using (var steam = new FileStream(path, FileMode.Create))
                {
                    await file.CopyToAsync(steam);
                }

                productDto.ImageUrl = String.Concat("/images/", file.FileName);
                _manager.ProductService.CreateProduct(productDto);
                return RedirectToAction("Index");
            }
            return View();
        }
        public IActionResult Update([FromRoute(Name = "id")] int id)
        {
            ViewBag.Categories = GetCategoriesSelectList();
            var model = _manager.ProductService.GetOneProductForUpdate(id, false);
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update([FromForm] ProductDtoForUpdate productDto, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                string path = Path.Combine(Directory.GetCurrentDirectory(), 
                "wwwroot", "images", file.FileName);

                using (var steam = new FileStream(path, FileMode.Create))
                {
                    await file.CopyToAsync(steam);
                }

                productDto.ImageUrl = String.Concat("/images/", file.FileName);
                _manager.ProductService.UpdateOneProduct(productDto);
                return RedirectToAction("Index");
            }
            return View();
        }
        [HttpGet]
        public IActionResult Delete([FromRoute(Name = "id")] int id)
        {
            _manager.ProductService.DeleteOneProduct(id);
            return RedirectToAction("Index");
        }
    }
}

store-app/Components/CategoriesMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;

namespace store_app.Components
{
    public class CategoriesMenuViewComponent: ViewComponent
    {
        public readonly IServiceManager _manager;

        public CategoriesMenuViewComponent(IServiceManager manager)
        {
            _manager = manager;
        }

        public IViewComponentResult Invoke()
        {
            var categories = _manager.CategoryService.GetAllCategories(false);
            return View(categories);
        }
    }
}

store-app/Components/ProductFilterMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace store_app.Components
{
    public class ProductFilterMenuViewComponent: ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

store-app/Controllers/ProductController.cs
using Entities.Models;
using Entities.RequestParameters;
using Microsoft.AspNetCore.Mvc;
using Repositories.Contracts;
using Services.Contracts;
using store_app.Models;


namespace store_app.Controllers
{
    public class ProductController: Controller
    {
        private readonly IServiceManager _manager;

        public ProductController(IServiceManager manager)
        {
            _manager = manager;
        }

        public ActionResult Index(ProductRequestParameters p)
        {
            var products = _manager.ProductService.GetAllProductsWithDetails(p);
            var pagination = new Pagination()
            {
                CurrentPage = p.PageNumber,
                ItemsPerPage = p.PageSize,
                TotalItems = _manager.ProductService.GetAllProducts(false).Count()
            };

            return View(new ProductListViewModel()
            {
                Products = products,
                Pagination = pagination
            });
        }

        public ActionResult Get([FromRoute(Name="id")] int id)
        {
            var model = _manager.ProductService.GetOneProduct(id, false);
            return View(model);
        }
    }
}

store-app/Views/Product/Get.cshtml
@model Product

<div class="row">
    <div class="col-md-12">
        <div class="text-center">
            <div class="display-6">
                @Model.ProductName
            </div>
            <img class="img-fluid shadow rounded-3 p-5 my-3" width="500" src="@Model?.ImageUrl" alt="@Model.ProductName" />
            <p class="lead text-danger">@Model.Price.ToString("c")</p>
            <p class="lead text-center my-3">@Model.Summary</p>
        </div>
    </div>
</div>

<div class="text-center">
    <div class="btn-group">
        <a class="btn btn-outline-secondary" asp-controller="Home" asp-action="Index">
            <i class="fa-solid fa-house"></i>
            Home
        </a>
        <form id="@Model.ProductId" asp-page="/cart" method="post">
            <input type="hidden" asp-for="ProductId" />
            <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
            <button type="submit" class="btn btn-outline-secondary rounded-0">
                <i class="fa fa-cart-plus"></i>
                Add To Cart
            </button>
        </form>
        <a class="btn btn-outline-secondary" asp-controller="Product" asp-action="Index">
            <i class="fa-solid fa-list"></i>
            Products
        </a>
    </div>
</div>

@section Header
{
    <div>
        Only For Get
    </div>
}

store-app/Views/Product/Index.cshtml
@model ProductListViewModel

@section Footer
{
    <div>Only For Index</div>
}

<div class="row">
    <div class="col-md-3">
        @await Component.InvokeAsync("CategoriesMenu")
        @await Component.InvokeAsync("ProductFilterMenu")
        <div products="" number="3"></div>
    </div>
    <div class="col-md-9">
        <div class="row">
            @foreach (Product prd in Model.Products)
            {
                <partial name="_ProductCard" model="@prd" />
            }
        </div>
        <div>
            <div page-model="@Model?.Pagination" page-action="Index" page-classes-enabled="true" page-class="btn"
                page-class-normal="btn-outline-dark" page-class-selected="btn-primary" class="btn-group">
            </div>
        </div>
    </div>
</div>